### ISSUE TITLE
[Bug] Mining Shaft into Crash

### ISSUE THREAD

**Issue by Boithatscold** [BusinessmenPlus/BusinessElitePlus#2]
Please Name your issue in the bar above ^^^^^^:EX: [bug] Crash mining a Shaft
#### Issue Description:

Crash - 
#### What Happens:
Shaft on a stripped log tried mining it

#### What you Expected to happen:

Crash
#### Steps to Reproduce in detail:
1.Rubber log strip
2.Put a shaft on it
3.Mine

Crash
...
#### Does it happen in Single Player: (yes or no) Please test
[ ] Yes

[ ] No

#### Does it happen on the Server: (yes or no)
[ ] Yes
yes
[ ] No

#### Pack Versions: Ex(V165.1.0.1)
(DO NOT LEAVE BLANK) 
1.19.2 .0.0.1
Latest
#### Mods Effected: Ex: (Quark, AE2, ect) 
(DO NOT LEAVE BLANK)

IC2 and Create
#### Your most recent log file where the issue was present or a screenshot of the issue:  ex: (log folder or crash reports or screenshot folder)
(DO NOT LEAVE BLA
[2022-11-17-2.log](https://github.com/BusinessmenPlus/BusinessElitePlus/files/10035161/2022-11-17-2.log)
NK. If you dont know ask for help in our discord)

[Pastebin/Gist/Pictures LINK here]

**Comment by DaemonUmbra** [comment]
I'm not seeing a crash here, could you reproduce the error and then provide ``C:\Users\aryan\curseforge\minecraft\Install\launcher_log.txt`` please.

**Comment by YOYOK9** [comment]
This was an issue with Oculus, removing it will fix the crash. it will be removed in the next update all together
