### ISSUE TITLE
digiminer from mek (bug)

### ISSUE THREAD

**Issue by Berndarmin** [BusinessmenPlus/BusinessElitePlus#4]
#### Issue Description:
can not craft a digiminer from mek recipe is broken

#### What Happens:
nothing can not craft

#### What you Expected to happen:
to craft a digiminer

#### Steps to Reproduce in detail:

1.tried on a crafting table 
2.tried to auto craft with AE2 cant make a pattern to auto craft
3.will not work with and 3x3 crafting gride

#### Does it happen in Single Player:

- [ ] Yes
- [x] No

#### Does it happen on the Server:

- [x] Yes
- [ ] No

**Comment by YOYOK9** [comment]
Please add more info.

**Comment by Berndarmin** [comment]
added more info

**Comment by YOYOK9** [comment]
Screen shots? logs?  pack version?

**Comment by Berndarmin** [comment]
added screen shots

**Comment by Berndarmin** [comment]
not sure on pack version but most up to date pack

**Comment by YOYOK9** [comment]
Fixed in newest pack
