### ISSUE TITLE
[Bug] Crash with AMD & Create

### ISSUE THREAD

**Issue by Berndarmin** [BusinessmenPlus/BusinessElitePlus#5]
#### Issue Description:
game crashes to desk top as soon as the world loads

#### What Happens:
game crashes to desk top as soon as the world loads

#### What you Expected to happen:
not to crash

#### Steps to Reproduce in detail:
1.load the multiplayer world
2.load the multiplayer world
3.load the multiplayer world

#### Does it happen in Single Player:

- [ ] Yes
- [x] No

#### Does it happen on the Server:

- [x] Yes
- [ ] No

#### Pack Version(s):

1.19.2-0.0.7
#### Mods Affected:
 
unknowen
#### Your most recent log file where the issue was present or a screenshot of the issue:
i uninstalled java and the mod pack and reinstallled clean for both 
![image](https://user-images.githubusercontent.com/72366006/208981598-d1e1dc10-cf4c-4234-a8cf-6ec448fe4621.png)
[hs_err_pid3124.log](https://github.com/BusinessmenPlus/BusinessElitePlus/files/10280402/hs_err_pid3124.log)

**Comment by YOYOK9** [comment]
Try lowering the allocated ram to 8gb then trying again

**Comment by Berndarmin** [comment]
![image](https://user-images.githubusercontent.com/72366006/208983926-5e32a04e-22f0-4875-b6f7-416b31a3d381.png)
sorry no that did work

**Comment by DaemonUmbra** [comment]
Investigation Notes (will be updated to prevent spamming webhooks, check GH for latest):

It appears to be something in Bern's base... didn't crash until I TPed to his location

**Comment by DaemonUmbra** [comment]
Try switching your Flywheel backend to BATCHED in the client config
