### ISSUE TITLE
[Bug] yellorite in mek machines

### ISSUE THREAD

**Issue by nightstalker6669** [BusinessmenPlus/BusinessElitePlus#7]
#### Issue Description:
yellorite comes out as uranium in mek machines

#### What Happens:
yellorite comes out as uranium in mek machines

#### What you Expected to happen:
yellorite to come out as yellorium ingots

#### Steps to Reproduce in detail:

1.put in yellorite to mek machine

#### Does it happen in Single Player:

- [ ] Yes
- [ ] No
- [x ] idk

#### Does it happen on the Server:

- [x ] Yes
- [ ] No

#### Mods Affected:
 
mek, extreme reactors

**Comment by DaemonUmbra** [comment]
Test in single player please...
Yes and No are the only options for a reason.

**Comment by YOYOK9** [comment]
Its an ore dict ussue.

**Comment by YOYOK9** [comment]
Fixed in version 1.19.2-0.0.8
