### ISSUE TITLE
[Bug] Cannot reach spawn in new world

### ISSUE THREAD

**Issue by SneakyDevil** [BusinessmenPlus/BusinessElitePlus#9]
#### Issue Description:
Stuck in mining/lobby/fishing the /spawn command doesn't exist

#### What Happens:
load up new world

#### What you Expected to happen:
play minecraft

#### Steps to Reproduce in detail:

1.create new world
2.
3.

#### Does it happen in Single Player:

- [x ] Yes
- [ ] No

#### Does it happen on the Server:

- [ ] Yes
- [ ] No

**Comment by YOYOK9** [comment]
Which pack version is this?

**Comment by SneakyDevil** [comment]
the default pack on curseforge

**Comment by YOYOK9** [comment]
I recently update some 1.19.2 alphas, that why I ask. Assuming its the 1.18.2 version?

**Comment by SneakyDevil** [comment]
![image](https://github.com/BusinessmenPlus/BusinessElitePlus/assets/11374726/04d81583-2c6b-4422-a258-71169327bdee)

**Comment by SneakyDevil** [comment]
oh that's wierd it deleted my pictures and version number in the OP

**Comment by YOYOK9** [comment]
Could have sworn this issue was fixed, Unfortunately I have moved to 1.19.2 now. Hopefully will be posting a beta version in a few days. 

Something you can do tho, is delete the lobby/fishing/mining world mod from the pack. Thought I had.

**Comment by SneakyDevil** [comment]
No problem, can do. Thanks!
